# Copyright (c) 2026 George Sapkin
#
# SPDX-License-Identifier: GPL-2.0-only

lassign $argv vm_name

set timeout 10
spawn virsh console $vm_name

expect {
    "Connected to domain" { exp_continue }
    "Escape character is" { send "\r" }
    timeout { exit 1 }
}

set timeout 60
expect {
    "Please press Enter to activate this console" {
        send "\r"
        exp_continue
    }
    -re "root@.*#" {}
    timeout { exit 1 }
}

set timeout -1
interact
